### ISSUE TITLE
Can't minify file

### ISSUE THREAD

**Issue by sufuf3** [PeterDaveHello/web-minify-helper#16]
I got the error message when I try to minify the https://github.com/sourcelair/xterm.js/blob/0.4/src/xterm.js
The error message shows as following:
```
$ ~/web-minify-helper/minify.sh --no-map
Scaning direcotry...
Finding js to be compressed under . ...
Compressing xterm.js ...
Parse error at xterm.js:419,24
    ev.stopPropagation[();
                        ^
SyntaxError: Unexpected token: punc ())
    at JS_Parse_Error.Object.defineProperty.get (eval at <anonymous> (/home/sjfu/web-minify-helper/node_modules/uglify-js/tools/node.js:27:1), <anonymous>:86:23)
    at /home/sjfu/web-minify-helper/node_modules/uglify-js/bin/uglifyjs:384:39
    at time_it (/home/sjfu/web-minify-helper/node_modules/uglify-js/bin/uglifyjs:620:15)
    at /home/sjfu/web-minify-helper/node_modules/uglify-js/bin/uglifyjs:345:9
    at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:380:3)
Parse error at xterm.js:419,25
SyntaxError: Unexpected token punc «;», expected arrow «=>»
Error
    at new JS_Parse_Error (eval at <anonymous> (/home/sjfu/web-minify-helper/node_modules/uglify-js-harmony/tools/node.js:28:1), <anonymous>:1928:18)
    at js_error (eval at <anonymous> (/home/sjfu/web-minify-helper/node_modules/uglify-js-harmony/tools/node.js:28:1), <anonymous>:1936:11)
    at croak (eval at <anonymous> (/home/sjfu/web-minify-helper/node_modules/uglify-js-harmony/tools/node.js:28:1), <anonymous>:2589:9)
    at token_error (eval at <anonymous> (/home/sjfu/web-minify-helper/node_modules/uglify-js-harmony/tools/node.js:28:1), <anonymous>:2597:9)
    at expect_token (eval at <anonymous> (/home/sjfu/web-minify-helper/node_modules/uglify-js-harmony/tools/node.js:28:1), <anonymous>:2610:9)
    at arrow_function (eval at <anonymous> (/home/sjfu/web-minify-helper/node_modules/uglify-js-harmony/tools/node.js:28:1), <anonymous>:2926:9)
    at maybe_assign (eval at <anonymous> (/home/sjfu/web-minify-helper/node_modules/uglify-js-harmony/tools/node.js:28:1), <anonymous>:4164:20)
    at expression (eval at <anonymous> (/home/sjfu/web-minify-helper/node_modules/uglify-js-harmony/tools/node.js:28:1), <anonymous>:4198:20)
    at subscripts (eval at <anonymous> (/home/sjfu/web-minify-helper/node_modules/uglify-js-harmony/tools/node.js:28:1), <anonymous>:4024:24)
    at subscripts (eval at <anonymous> (/home/sjfu/web-minify-helper/node_modules/uglify-js-harmony/tools/node.js:28:1), <anonymous>:4015:20)
local compressor failed, now try to compress with javascript-/cssminifier.com
```
When I do cdnjs/cdnjs#10764, I can minify all the files in v0.0.2~v2.0.0 except v0.4 of `xterm.js`.
Could you help me fix this issue?
Thanks.

**Comment by PeterDaveHello** [comment]
Please report to `uglify-js`, this is jut a wrapper.
